import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";
import { google } from 'googleapis';

dotenv.config();

const app = express();
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));
const PORT = 3000;

// Helper to get Gemini AI Client dynamically (allows client-supplied API key or OAuth access token)
function getAIClient(req: express.Request): any {
  const key = process.env.GEMINI_API_KEY;
  if (!key) {
    throw new Error("No Gemini API key found. Please configure the GEMINI_API_KEY in the workspace Settings.");
  }

  const trimmedKey = key.trim();
  const cleanKey = trimmedKey.replace(/^["']|["']$/g, '');

  return new GoogleGenAI({ 
    apiKey: cleanKey,
    httpOptions: { headers: { 'User-Agent': 'aistudio-build' } }
  });
}

// Helper to safely execute AI requests and handle rate limits gracefully
async function safeGenerateContent(aiInstance: any, options: any, fallbackData: any) {
  try {
    const response = await aiInstance.models.generateContent(options);
    return JSON.parse(response.text || JSON.stringify(fallbackData));
  } catch (err: any) {
    if (err?.message?.includes("429") || err?.message?.includes("quota") || err?.status === 429 || err?.status === "RESOURCE_EXHAUSTED") {
      console.warn("Gemini API Rate Limit hit. Using fallback data to maintain app functionality.");
      return fallbackData;
    }
    throw err;
  }
}

// ---------------------------------------------------------------------------
// 1. Orchestrator + Decomposer Agent (Task Breakdown)
// ---------------------------------------------------------------------------
app.post("/api/agents/decompose", async (req, res) => {
  const { title, description, deadline, preferences } = req.body;
  
  try {
    const aiInstance = getAIClient(req);
    const prompt = `Perform a cooperative multi-agent analysis and decomposition on the task below:
Task details:
- Title: ${title}
- Description: ${description || 'No description provided.'}
- Deadline: ${deadline || 'No deadline provided.'}
- User Context/Preferences: ${JSON.stringify(preferences || {})}

Collaborative sequence to execute:
1. "Perceiving agent": Gathers the raw input details, constraints, deadlines, and environmental state to establish baseline context.
2. "Prioritizing agent": Refines metrics for urgency, impact, effort, and provides a priority rating based on the perceived state.
3. "Decomposing Agent": Breaks down the complex target into a logical sequence of 3 to 7 actionable, time-boxed subtasks.
4. "Planning agent": Recommends execution timeframes, optimal peak productivity hours, and pacing strategies.
5. "Autonomous task automation agent": Defines automated triggers, drafts system action templates, or sets context alarms.
6. "Orchestrating agent": Coordinates the sequence, performs final quality assurance, and validates that all deliverables are cohesive.`;

    const result = await safeGenerateContent(aiInstance, {
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        systemInstruction: "You are the NEXUS Multi-Agent Orchestrator. You coordinate a multi-agent system comprising: 'Perceiving agent', 'Prioritizing agent', 'Decomposing Agent', 'Planning agent', 'Autonomous task automation agent', and 'Orchestrating agent'. Each agent must perform its specific role sequentially to analyze, prioritize, decompose, plan, and draft automations for the task. You must return the final output strictly adhering to the JSON schema, with detailed collaborative logs for each agent.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            subtasks: {
              type: Type.ARRAY,
              description: "Actionable steps generated by the Decomposing Agent",
              items: {
                type: Type.OBJECT,
                properties: {
                  id: { type: Type.STRING, description: "Unique short subtask identifier, e.g. 'sub-1', 'sub-2'" },
                  title: { type: Type.STRING, description: "The subtask title" },
                  estimatedMinutes: { type: Type.NUMBER, description: "Estimated focus time in minutes" },
                  completed: { type: Type.BOOLEAN, description: "Initialize to false" }
                },
                required: ["id", "title", "estimatedMinutes", "completed"]
              }
            },
            urgency: { type: Type.NUMBER, description: "Urgency score from 1 to 10 computed by 'Prioritizing agent'" },
            impact: { type: Type.NUMBER, description: "Impact score from 1 to 10 computed by 'Prioritizing agent'" },
            effort: { type: Type.NUMBER, description: "Effort score from 1 to 10 computed by 'Prioritizing agent'" },
            agentLogs: {
              type: Type.OBJECT,
              properties: {
                perceivingAgentLog: { type: Type.STRING, description: "Environmental context and constraints perception analysis." },
                prioritizingAgentLog: { type: Type.STRING, description: "Urgency, impact, effort prioritizer reasoning." },
                decomposingAgentLog: { type: Type.STRING, description: "Decomposing agent details on how subtasks are structured." },
                planningAgentLog: { type: Type.STRING, description: "Schedule recommendations, focus block hours suggested." },
                autonomousAutomationLog: { type: Type.STRING, description: "Self-directed background triggers, alarms, or email draft recommendations." },
                orchestratingAgentLog: { type: Type.STRING, description: "System orchestration quality assurance and pipeline validation summary." }
              },
              required: [
                "perceivingAgentLog",
                "prioritizingAgentLog",
                "decomposingAgentLog",
                "planningAgentLog",
                "autonomousAutomationLog",
                "orchestratingAgentLog"
              ]
            }
          },
          required: ["subtasks", "urgency", "impact", "effort", "agentLogs"]
        }
      }
    }, {
      subtasks: [
        { id: "sub-1-fb", title: "Draft requirements", estimatedMinutes: 30, completed: false },
        { id: "sub-2-fb", title: "Complete task", estimatedMinutes: 60, completed: false }
      ],
      urgency: 5, impact: 5, effort: 5,
      agentLogs: {
        perceivingAgentLog: "API Quota exceeded. Using offline fallback mode.",
        prioritizingAgentLog: "API Quota exceeded. Assigned default priority.",
        decomposingAgentLog: "API Quota exceeded. Basic decomposition applied.",
        planningAgentLog: "API Quota exceeded. Suggest standard working hours.",
        autonomousAutomationLog: "API Quota exceeded. Background tasks suspended.",
        orchestratingAgentLog: "Offline fallback orchestrator engaged."
      }
    });

    res.json(result);
  } catch (error: any) {
    console.error("Decomposer error:", error);
    res.status(500).json({ error: error.message });
  }
});

// ---------------------------------------------------------------------------
// 2. Scheduler Agent (Focus Blocks)
// ---------------------------------------------------------------------------
app.post("/api/agents/schedule", async (req, res) => {
  const { task, subtasks, preferences, existingEvents } = req.body;
  
  try {
    const aiInstance = getAIClient(req);
    const prompt = `Propose Focus Blocks (calendar slots) to complete these subtasks before the deadline.
Deadline: ${task.deadline}
Subtasks: ${JSON.stringify(subtasks)}
User Preferences (Peak hours, DND): ${JSON.stringify(preferences)}
Existing Events: ${JSON.stringify(existingEvents || [])}`;

    const result = await safeGenerateContent(aiInstance, {
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        systemInstruction: "You are the NEXUS Scheduler Agent. Propose calendar blocks avoiding existing events and respecting user preferences. Output JSON.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              subtaskId: { type: Type.STRING, description: "Match the subtask index/title if id missing" },
              start: { type: Type.STRING, description: "ISO 8601 string" },
              end: { type: Type.STRING, description: "ISO 8601 string" }
            },
            required: ["start", "end"]
          }
        }
      }
    }, []);

    res.json(result);
  } catch (error: any) {
    console.error("Scheduler error:", error);
    res.status(500).json({ error: error.message });
  }
});

// ---------------------------------------------------------------------------
// 3. Voice Parsing (NEXUS Voice Agent)
// ---------------------------------------------------------------------------
app.post("/api/agents/voice", async (req, res) => {
  const { transcript, history } = req.body;
  
  try {
    const aiInstance = getAIClient(req);
    
    // Format history for Gemini
    const contents: any[] = (history || []).map((msg: any) => ({
      role: msg.role === 'user' ? 'user' : 'model',
      parts: [{ text: msg.text }]
    }));

    contents.push({
      role: "user",
      parts: [{ text: `Current Time: ${new Date().toISOString()}\nUser input: "${transcript}"` }]
    });

    const result = await safeGenerateContent(aiInstance, {
      model: "gemini-2.5-flash",
      contents,
      config: {
        systemInstruction: "You are the NEXUS AI voice assistant. Converse naturally with the user. If the user asks to create, add, or remind them of a task, include the 'createTask' object. If they don't specify a time, you can ask them for a deadline in your responseText, or just create it without a deadline. Always provide a conversational 'responseText' that will be spoken back to the user.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            responseText: { type: Type.STRING, description: "The spoken response to the user" },
            createTask: {
              type: Type.OBJECT,
              description: "Include this ONLY if a task should be created based on the user's input",
              properties: {
                title: { type: Type.STRING },
                deadline: { type: Type.STRING, description: "ISO 8601 date, if a timeframe was mentioned" },
                priorityScore: { type: Type.NUMBER }
              },
              required: ["title"]
            }
          },
          required: ["responseText"]
        }
      }
    }, {
      responseText: "I'm sorry, the AI API is currently rate limited. Please try again in a few moments."
    });
    res.json(result);
  } catch (error: any) {
    console.error("Voice parsing error:", error);
    res.status(500).json({ error: error.message });
  }
});


// ---------------------------------------------------------------------------
// 4. Nudge Agent (Context-Aware Notifications)
// ---------------------------------------------------------------------------
app.post("/api/agents/nudge", async (req, res) => {
  const { task, userState } = req.body;
  try {
    const aiInstance = getAIClient(req);
    const result = await safeGenerateContent(aiInstance, {
      model: "gemini-2.5-flash",
      contents: `Task: ${JSON.stringify(task)}\nUser State: ${JSON.stringify(userState)}`,
      config: {
        systemInstruction: "You are the NEXUS Nudge Agent. Generate a context-aware nudge message (max 2 sentences) and a suggested micro-action.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            message: { type: Type.STRING },
            suggestedAction: { type: Type.STRING }
          }
        }
      }
    }, {
      message: "It looks like you're offline or quota exceeded. Time for a quick break?",
      suggestedAction: "Stretch for 2 minutes"
    });
    res.json(result);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// ---------------------------------------------------------------------------
// 5. Execution Agent (Calendar/Email Automations)
// ---------------------------------------------------------------------------
app.post("/api/agents/execute", async (req, res) => {
  const { actionType, details } = req.body;
  try {
    const aiInstance = getAIClient(req);
    const result = await safeGenerateContent(aiInstance, {
      model: "gemini-2.5-flash",
      contents: `Action: ${actionType}\nDetails: ${JSON.stringify(details)}`,
      config: {
        systemInstruction: "You are the NEXUS Execution Agent. Draft an email, document, action plan, code, outline, or calendar event description based on the request.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            status: { type: Type.STRING },
            generatedContent: { type: Type.STRING }
          }
        }
      }
    }, {
      status: "fallback",
      generatedContent: "Could not generate content due to API rate limits. Please try again later."
    });
    
    const parsed = result;

    if (actionType === 'generate_doc') {
      const authHeader = req.headers.authorization;
      if (!authHeader || !authHeader.startsWith('Bearer ')) {
        throw new Error('Google Workspace access token required for document generation.');
      }
      const token = authHeader.split(' ')[1];
      const authClient = new google.auth.OAuth2();
      authClient.setCredentials({ access_token: token });
      const docs = google.docs({ version: 'v1', auth: authClient });

      const doc = await docs.documents.create({
        requestBody: {
          title: `NEXUS Summary: ${details?.taskTitle || 'Task'}`
        }
      });

      const documentId = doc.data.documentId;
      if (documentId && parsed.generatedContent) {
        await docs.documents.batchUpdate({
          documentId: documentId,
          requestBody: {
            requests: [
              {
                insertText: {
                  location: { index: 1 },
                  text: parsed.generatedContent
                }
              }
            ]
          }
        });
      }

      parsed.generatedContent = `Google Doc Generated: "${doc.data.title}"\n\nLink: https://docs.google.com/document/d/${documentId}\n\nContent Preview:\n${parsed.generatedContent}`;
    }

    res.json(parsed);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// ---------------------------------------------------------------------------
// 5b. Dynamic Actions Generator (Action Center)
// ---------------------------------------------------------------------------
app.post("/api/agents/dynamic_actions", async (req, res) => {
  const { taskTitle, taskDescription } = req.body;
  try {
    const aiInstance = getAIClient(req);
    const result = await safeGenerateContent(aiInstance, {
      model: "gemini-2.5-flash",
      contents: `Task Title: ${taskTitle}\nTask Description: ${taskDescription || 'None'}`,
      config: {
        systemInstruction: "You are the NEXUS Action Generation Agent. Based on the task context, suggest exactly 3 unique, specific, and highly helpful 'supportive actions' that an AI could perform on behalf of the user to accelerate their work when a deadline is imminent. Examples: creating flashcards for studying, generating boilerplate code for software tasks, drafting an essay outline, compiling references, etc. Return them as a JSON array of objects.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              id: { type: Type.STRING, description: "A unique identifier string without spaces, e.g. 'generate_summary'" },
              label: { type: Type.STRING, description: "A short button label, e.g. 'Draft Summary'" },
              actionText: { type: Type.STRING, description: "Action completion phrase, e.g. 'draft a summary of the topic'" },
              needsCreds: { type: Type.BOOLEAN, description: "True if it requires external API access like Google Docs/Drive, False if it just generates text/code locally." },
              completionText: { type: Type.STRING, description: "Text to show when done, e.g. 'Your summary is ready.'" },
              outputMock: { type: Type.STRING, description: "A short placeholder text of what the output would look like, e.g. 'Summary: This is a placeholder summary...'" }
            },
            required: ["id", "label", "actionText", "needsCreds", "completionText", "outputMock"]
          }
        }
      }
    }, [
      { id: "fallback_1", label: "Generate Summary", actionText: "generate a summary", needsCreds: false, completionText: "Summary ready", outputMock: "Fallback Summary" }
    ]);
    res.json(result);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// ---------------------------------------------------------------------------
// 6. Reflection Agent (Insights & Analytics)
// ---------------------------------------------------------------------------
app.post("/api/agents/reflect", async (req, res) => {
  const { completedTasks } = req.body;
  try {
    const aiInstance = getAIClient(req);
    const result = await safeGenerateContent(aiInstance, {
      model: "gemini-2.5-flash",
      contents: `Completed Tasks: ${JSON.stringify(completedTasks)}`,
      config: {
        systemInstruction: "You are the NEXUS Reflection Agent. Analyze the completed tasks and provide 3 actionable insights on the user's productivity patterns.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            insights: {
              type: Type.ARRAY,
              items: { type: Type.STRING }
            }
          }
        }
      }
    }, {
      insights: ["Keep up the good work!", "Take breaks when needed.", "API Quota limited."]
    });
    res.json(result);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
});

// ---------------------------------------------------------------------------
// 7. Auto-Orchestrator (Global Re-Prioritization & Planning)
// ---------------------------------------------------------------------------
app.post("/api/agents/reprioritize", async (req, res) => {
  const { tasks } = req.body;
  if (!tasks || !Array.isArray(tasks)) {
    return res.status(400).json({ error: "Invalid tasks array provided." });
  }

  try {
    const aiInstance = getAIClient(req);
    const result = await safeGenerateContent(aiInstance, {
      model: "gemini-2.5-flash",
      contents: `Current tasks: ${JSON.stringify(tasks)}\nCurrent Time: ${new Date().toISOString()}`,
      config: {
        systemInstruction: "You are the NEXUS Orchestrator Agent. You analyze the list of tasks. For each task, calculate/re-evaluate its priority score (1.0 to 10.0 scale, where 10 is highest), urgency, impact, and effort. If a task has no subtasks (is empty or length is 0) and is pending/in-progress, generate 3 to 5 clear, sequential, and highly actionable subtasks (each with a unique id, title, estimatedMinutes, and completed: false). Provide a short overall focus plan under globalPlanInsight.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            tasks: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  id: { type: Type.STRING },
                  priorityScore: { type: Type.NUMBER },
                  urgency: { type: Type.NUMBER },
                  impact: { type: Type.NUMBER },
                  effort: { type: Type.NUMBER },
                  subtasks: {
                    type: Type.ARRAY,
                    items: {
                      type: Type.OBJECT,
                      properties: {
                        id: { type: Type.STRING },
                        title: { type: Type.STRING },
                        estimatedMinutes: { type: Type.NUMBER },
                        completed: { type: Type.BOOLEAN }
                      }
                    }
                  }
                },
                required: ["id", "priorityScore", "urgency", "impact", "effort"]
              }
            },
            globalPlanInsight: { type: Type.STRING }
          },
          required: ["tasks", "globalPlanInsight"]
        }
      }
    }, {
      tasks: tasks.map((t: any) => ({
        id: t.id,
        priorityScore: 5, urgency: 5, impact: 5, effort: 5,
        subtasks: t.subtasks || []
      })),
      globalPlanInsight: "AI prioritization is currently unavailable due to rate limits."
    });

    res.json(result);
  } catch (error: any) {
    console.error("Reprioritization API error:", error);
    const msg = error.message || String(error);
    const isPermissionError = msg.includes("denied access") || msg.includes("403") || msg.includes("PERMISSION_DENIED");
    res.status(isPermissionError ? 403 : 500).json({ 
      error: isPermissionError ? "PERMISSION_DENIED" : "API_ERROR", 
      message: error.message || "Failed to reprioritize tasks." 
    });
  }
});

// ---------------------------------------------------------------------------
// 8. Planning Agent (Generate Realistic Task Execution Plan)
// ---------------------------------------------------------------------------
app.post("/api/agents/generate-plan", async (req, res) => {
  const { tasks } = req.body;
  if (!tasks || !Array.isArray(tasks)) {
    return res.status(400).json({ error: "Invalid tasks array provided." });
  }

  const pendingTasks = tasks.filter(t => t.status !== 'completed');
  if (pendingTasks.length === 0) {
    return res.json({
      id: "plan-" + Math.random().toString(36).substring(2, 11),
      objective: "No active tasks found. Clear horizon!",
      items: [],
      createdAt: new Date().toISOString(),
      status: "completed",
      executionLogs: []
    });
  }

  try {
    const aiInstance = getAIClient(req);
    const result = await safeGenerateContent(aiInstance, {
      model: "gemini-2.5-flash",
      contents: `Generate a realistic, structured, chronologically sequenced execution plan to complete all pending tasks before their deadlines.
Current tasks: ${JSON.stringify(pendingTasks)}
Current Time: ${new Date().toISOString()}`,
      config: {
        systemInstruction: "You are the NEXUS Lead Planning Agent. You examine the tasks, their deadlines, priority scores, and subtasks. You must generate a highly structured sequential list of specific, time-boxed schedule items (plan items) that allows the user to complete all tasks and subtasks efficiently. Ensure earlier deadlines and higher priority tasks are scheduled first. Each scheduled item must map to a task (and optionally a specific subtask) with a logical duration, relative date, time slot, and description. Output JSON.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            id: { type: Type.STRING },
            objective: { type: Type.STRING, description: "A high-level sentence stating the core objective of this schedule." },
            items: {
              type: Type.ARRAY,
              description: "Chronologically sorted task plan items",
              items: {
                type: Type.OBJECT,
                properties: {
                  id: { type: Type.STRING },
                  taskId: { type: Type.STRING },
                  taskTitle: { type: Type.STRING },
                  subtaskId: { type: Type.STRING, description: "Optional subtask ID if mapping to a subtask" },
                  subtaskTitle: { type: Type.STRING, description: "Optional subtask title" },
                  timeSlot: { type: Type.STRING, description: "Formatted time range in 12-hour format with am/pm, e.g. '9:00 am - 10:30 am' or '2:00 pm - 3:15 pm'" },
                  durationMinutes: { type: Type.NUMBER, description: "Minutes allotted for this session" },
                  date: { type: Type.STRING, description: "Target date in format YYYY-MM-DD or relative day" },
                  description: { type: Type.STRING, description: "Specific actionable objective of this focus block" },
                  status: { type: Type.STRING, description: "Must be 'pending'" }
                },
                required: ["id", "taskId", "taskTitle", "timeSlot", "durationMinutes", "date", "description", "status"]
              }
            }
          },
          required: ["id", "objective", "items"]
        }
      }
    }, {
      id: "plan-" + Math.random().toString(36).substring(2, 11),
      objective: "API Quota exceeded. Please try again later.",
      items: pendingTasks.map((t: any, idx: number) => {
        const startH = (9 + idx) % 24;
        const endH = (10 + idx) % 24;
        const formatH = (h: number) => `${h % 12 || 12}:00 ${h >= 12 ? 'pm' : 'am'}`;
        return {
          id: "pi-" + idx,
          taskId: t.id,
          taskTitle: t.title,
          timeSlot: `${formatH(startH)} - ${formatH(endH)}`,
          durationMinutes: 60,
          date: new Date().toISOString().split('T')[0],
          description: "Focus session for " + t.title,
          status: "pending"
        };
      })
    });

    res.json(result);
  } catch (error: any) {
    console.error("Plan generation API error:", error);
    res.status(500).json({ error: error.message || "Failed to generate plan." });
  }
});

// ---------------------------------------------------------------------------
// 8. AI-Driven Intake Agent
// ---------------------------------------------------------------------------
app.post("/api/agents/intake", async (req, res) => {
  const { prompt, document } = req.body;
  
  try {
    const aiInstance = getAIClient(req);
    const contents: any[] = [];
    
    if (document) {
      // document should have { inlineData: { data: string, mimeType: string } }
      contents.push({
        role: "user",
        parts: [
          document,
          { text: "Analyze the attached document." }
        ]
      });
    }
    
    let textPrompt = prompt || "Analyze this task request.";
    contents.push({
      role: "user",
      parts: [{ text: `Current Time: ${new Date().toISOString()}\n\nRequest: ${textPrompt}` }]
    });

    const result = await safeGenerateContent(aiInstance, {
      model: "gemini-2.5-flash",
      contents,
      config: {
        systemInstruction: "You are the NEXUS AI Intake Agent. You extract task deadlines and calculate priority scores from frantic prompts and/or syllabus documents. Return an array of tasks. Priority score should be between 1 and 100 based on urgency and importance.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            tasks: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  title: { type: Type.STRING },
                  description: { type: Type.STRING },
                  deadline: { type: Type.STRING, description: "ISO 8601 formatted date if present" },
                  priorityScore: { type: Type.NUMBER, description: "Calculated from 1-100 based on urgency" }
                },
                required: ["title", "priorityScore"]
              }
            }
          },
          required: ["tasks"]
        }
      }
    }, {
      tasks: [
        {
          title: "API Limit Exceeded (Fallback task)",
          description: "Could not parse document due to API limits. Please add tasks manually.",
          priorityScore: 50
        }
      ]
    });
    res.json(result);
  } catch (error: any) {
    console.error("AI Intake parsing error:", error);
    res.status(500).json({ error: error.message });
  }
});

// ---------------------------------------------------------------------------
// Vite Middleware
// ---------------------------------------------------------------------------
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
